source "https://rubygems.org"

gem "rack", ">= 3.0", "< 4"
gem "rackup"
gem "falcon"
gem "sinatra", "4.2.1"
gem "faraday", "2.14.0"
gem "faraday-retry", "2.4.0"
gem "faraday-net_http_persistent", "2.3.1"
